// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#if !defined(AFX_STDAFX_H__989B81C9_8AC5_11D3_ACEB_00805FFDB2A5__INCLUDED_)
#define AFX_STDAFX_H__989B81C9_8AC5_11D3_ACEB_00805FFDB2A5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

// Disable "identifier was truncated to '255' characters in the debug information"
// warning generated by stl
#pragma warning (disable : 4786)

#define VC_EXTRALEAN		// Exclude rarely-used stuff from Windows headers

#ifdef PCLIENT_MODULE_

  //
  // Client uses MFC
  //
  #include <afxwin.h>         // MFC core and standard components
  #include <afxext.h>         // MFC extensions
  #include <vfw.h>
  #ifndef _AFX_NO_AFXCMN_SUPPORT
  #include <afxcmn.h>			// MFC support for Windows Common Controls
  #endif // _AFX_NO_AFXCMN_SUPPORT

#else

  //
  // Server uses plain API
  //
  #include <windows.h>

#endif


//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif 
