//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by D:\psi\pclient\Poker.rc
//
#define ID_TIMER_LOGOUTEXIT             1
#define ID_TIMER_TESTLOGINLOGOUT        2
#define ID_TIMER_HEARTBEAT              3
#define IDD_ABOUTBOX                    103
#define IDD_ACTIONBAR                   104
#define IDD_LOGIN                       106
#define IDD_MOTD                        107
#define IDD_MOTD1                       108
#define IDR_MAINFRAME                   128
#define IDB_MASK                        130
#define IDB_CARDS                       131
#define IDB_LOGO                        132
#define IDB_BACK                        133
#define IDW_CHIMES                      134
#define IDW_CASHREG                     135
#define IDB_BACKGROUND                  136
#define IDD_LOGGINGIN                   137
#define IDD_WAITING                     137
#define IDB_ARROWUP                     138
#define IDB_ARROWLEFT                   139
#define IDD_CHAT                        140
#define IDB_ARROWRIGHT                  141
#define IDB_ARROWDOWN                   142
#define IDB_ARROWDOWNMASK               143
#define IDB_ARROWLEFTMASK               144
#define IDB_ARROWRIGHTMASK              145
#define IDB_ARROWUPMASK                 146
#define IDW_ALERT                       260
#define IDM_TABLEVIEW                   261
#define IDM_FLOORMAPVIEW                262
#define IDM_TABLEVIEW_DEBUG             262
#define IDR_ACCELERATOR1                264
#define IDD_BUYINQUERY                  265
#define IDD_POPULATEPDU                 267
#define IDB_BTN1                        270
#define IDB_CHECK                       271
#define IDB_CHECKMASK                   272
#define IDB_DEALERIMAGE                 274
#define IDB_DEALERMASK                  275
#define IDB_CORNERIMAGE                 276
#define IDB_CORNERMASK                  277
#define IDB_INVALIDCARD                 279
#define IDB_DOLLARIMAGE                 280
#define IDB_DOLLARMASK                  281
#define IDD_DIALOG1                     282
#define IDD_ACTIONBAR2                  283
#define IDW_YOURTURN                    284
#define IDD_OPTIONS                     285
#define IDD_PROMPTINPUT                 286
#define IDW_DEBUG                       287
#define IDD_FLOORMANMSG                 287
#define IDB_CHECKBTN                    288
#define IDB_CHECKBTNMASK                289
#define IDD_DIALOG2                     290
#define IDM_POPUP                       291
#define IDD_EDITCOMMENT                 292
#define IDC_TITLE                       1002
#define IDC_COPYRIGHT                   1003
#define IDC_STATIC1                     1005
#define IDC_PASSWORD                    1006
#define IDC_USERNAME                    1007
#define IDC_MESSAGEPANE                 1008
#define IDC_RICHEDIT1                   1009
#define IDC_PROMPT                      1010
#define IDC_LOW                         1011
#define IDC_HI                          1012
#define IDC_CHECKPOSTBLIND              1013
#define IDC_CHECKSITOUT                 1014
#define IDC_CHECKFOLD                   1015
#define IDC_EDITCHAT                    1016
#define IDS_SOCKETINITFAILED            1017
#define IDC_CHECKCALL                   1018
#define IDS_INVALIDNAMEORPASSWORD       1019
#define IDC_CHECKRAISE                  1020
#define IDC_TAB1                        1021
#define IDC_EDITPORT                    1022
#define IDS_LOGINFAILED                 1023
#define IDC_EDITHOST                    1024
#define IDC_CHIPS                       1025
#define IDC_LIST1                       1026
#define IDC_STATUSBAR                   1027
#define IDC_SAVEPASSWORD                1028
#define IDC_MUCKHAND                    1029
#define IDC_CHECK1                      1030
#define IDC_TAKEFOCUS                   1030
#define IDC_CHECK2                      1031
#define IDC_SETTINGS_DOCKACTIONBAR      1031
#define IDC_SPIN1                       1032
#define IDC_SCROLLBAR1                  1033
#define IDC_RAISESCROLLBAR              1034
#define IDC_GROUP1                      1035
#define IDC_RAISEAMOUNT                 1036
#define IDC_SETTINGS_SOUNDS             1037
#define IDC_SETTINGS_TTIPS              1038
#define IDC_SETTINGS_HORZACTIONBAR      1039
#define IDC_SETTINGS_EMAILADDRESS       1040
#define IDC_EDIT2                       1041
#define IDC_BTN_PLACEHOLDER1            1042
#define IDC_BTN_PLACEHOLDER2            1043
#define IDC_BTN_PLACEHOLDER3            1044
#define IDC_EDIT1                       1045
#define IDC_GROUPBOX_VERSION            1046
#define IDC_BTN_ALL                     1050
#define IDC_RADIO_ALL                   1053
#define IDC_RADIO_DEALER                1054
#define IDC_RADIO_USER                  1055
#define IDC_SETTINGS_DOCKCHATWND        1056
#define IDC_SETTINGS_DOCKCHATLEFT       1057
#define IDC_SLIDER1                     1058
#define IDC_EDIT_NOTE                   1059
#define IDC_CHECK_SYSTEMONLY            1118
#define ID_BET_AI                       32771
#define IDC_MOTD                        32772
#define ID_MOTD                         32774
#define ID_FLOORMAP                     32775
#define ID_TABLE                        32776
#define ID_SOUNDTOGGLE                  32777
#define ID_VIEW_BACKGROUND              32778
#define IDM_VIEW_BACKGROUND             32779
#define ID_RELOAD_CONFIGURATION         32780
#define ID_FAKE_PDUPLAYER               32782
#define ID_FAKE_PDUDEALCARDS            32783
#define ID_FAKE_PDUCOMMUNITYCARD        32784
#define ID_FAKE_PDUSHOWDOWN             32785
#define ID_FAKE_PDUBLINDPOST            32786
#define ID_FAKE_PDUERROR                32787
#define ID_FAKE_PDUBUYINQUERY           32788
#define ID_FAKE_PDUACTIONREQUEST        32789
#define ID_FAKE_PDUSTATUS               32790
#define ID_FAKE_PDUSITTING              32791
#define ID_FAKE_PDULOUNGEACCEPT         32794
#define ID_FAKE_PDUANNOUNCE             32795
#define ID_FAKE_PDULOGOUTWARNING        32796
#define ID_FAKE_PDULOGOUTCONFIRM        32797
#define ID_FAKE_PDUTABLEACCEPT          32799
#define ID_INDICATOR_ONLINE             32800
#define ID_FAKE_PDUBUTTON               32801
#define ID_INDICATOR_OFFLINE            32801
#define ID_TESTDOWNLOAD                 32802
#define ID_SPLITPOT                     32803
#define ID_OPTIONS                      32804
#define ID_REQUESTPREVHAND              32805
#define ID_REQUEST5HANDLOG              32806
#define ID_FAKEFOLD                     32807
#define ID_BUYIN                        32808
#define ID_TESTLOGINOUT                 32809
#define ID_ROOT                         32814
#define ID_SUPPORTEMAIL                 32815
#define ID_PAGEFLOORMAN                 32816
#define ID_EDITCOMMENT                  32817

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        293
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
